[package]
name = "traceroute_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.6", features = ["derive"] }
pnet = "0.29.0"
dns-lookup = "1.0.8"
url = "2.2.2"